[package]
name = "short_print"
path="src/lib.rs"
version = "0.1.0"
authors = ["idkhan <islamuddin@careermap.pk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]